trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: coocoofroggy/otalive
        tags: |
          $(tag)
    - task: CmdLine@2
      displayName: Save image to file
      inputs:
        script: 'docker save -o image.tar coocoofroggy/otalive'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: 'image.tar'
        ArtifactName: 'image.tar'
        publishLocation: 'Container'
- stage: Deploy
  displayName: Deploy
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      name: Default
    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'image.tar'
        downloadPath: '~'
    - task: Bash@3
      inputs:
        filePath: '~/otaliveupdater.sh'
