trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build & Deploy
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: SSH@0
      displayName: Test SSH
      inputs:
        sshEndpoint: 'OTA-Live-VM SSH'
        runOptions: 'commands'
        commands: 'echo Test'
        readyTimeout: '20000'
    - task: Docker@2
      displayName: Build image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: coocoofroggy/otalive
        tags: |
          $(tag)
    - task: CmdLine@2
      displayName: Save image to file
      inputs:
        script: 'docker save -o image.tar coocoofroggy/otalive'
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: 'OTA-Live-VM SSH'
        contents: 'image.tar'
        targetFolder: '/tmp/'
        readyTimeout: '20000'
        failOnEmptySource: true
    - task: SSH@0
      inputs:
        sshEndpoint: 'OTA-Live-VM SSH'
        runOptions: 'script'
        scriptPath: '~/otaliveupdater.sh'
        readyTimeout: '20000'